### ISSUE TITLE
Adding emphasis to text

### ISSUE THREAD

**Issue by EstherDeLoof** [OpenWebSlides/OpenWebSlides.github.io#12]
We're currently using markdown **emphasis** in the .md files, but this isn't rendered with a stronger layout in my browser.

**Comment by RubenVerborgh** [comment]
Can you point to an example where it doesn't work for you?

**Comment by EstherDeLoof** [comment]
Sure, https://github.com/OpenWebSlides/OpenWebSlides.github.io/blob/master/voordelen.md
