### ISSUE TITLE
mailing list

### ISSUE THREAD

**Issue by cljansse** [OpenWebSlides/OpenWebSlides.github.io#13]
How can people join the mailing list? Now when I click on mailing list I go to outlook to send an email to openwebslides@lists.ugent.be. Do I have to send a request here to be added to the list? And is my request directly sent to all the people in the mailing list, because we don't want that. There should be a clear way to automatically subscribe to the mailing list.

**Comment by RubenVerborgh** [comment]
I found the following instructions:

> Send a message to listserv@lists.ugent.be from the address you want to subscribe to the list.
> In the subject line of your message, type in: subscribe nameofthelist Firstname Name
—https://lists.ugent.be/wws/help/user

Could you please verify whether this works? If so, we can put up the instructions.

**Comment by EstherDeLoof** [comment]
Can we make this automatic in any way? Or are we limited to explaining this in full?

**Comment by RubenVerborgh** [comment]
I just got confirmation that @cljansse signed up, so at least it worked. We can provide a [link](mailto:listserv@lists.ugent.be?subject=openwebslides+Your+Name); possibly the lists.ugent.be website offers a form too.

**Comment by cljansse** [comment]
you should add subscribe before openwebslides in the subject line

**Comment by EstherDeLoof** [comment]
That works fine for me, how can I integrate this in our code?

**Comment by Beramos** [comment]
It is possible to add a button where people can click on to open their 
mailing client, I guess it is also possible to already add the message 
to the mail.

**Comment by RubenVerborgh** [comment]
@EstherDeLoof just
```html
<a href="mailto:listserv@lists.ugent.be?subject=subscribe%20openwebslides%20Your%20Name">subscribe</a>
```
or in Markdown
```markdown
 [subscribe](mailto:listserv@lists.ugent.be?subject=subscribe%20openwebslides%20Your%20Name)
```

**Comment by EstherDeLoof** [comment]
Perfect!
