### ISSUE TITLE
slides

### ISSUE THREAD

**Issue by cljansse** [OpenWebSlides/OpenWebSlides.github.io#14]
When I click on one of the slides (browser = firefox) on the ugent project tab then the slide opens but below and above I have a lot of black space. It would be prettier if this was not there, or white like the background. Also when I go to another tab and then I go back to the ugent project tab, the slide is still open. Maybe this should go automatically back to the overview of the slides?

**Comment by RubenVerborgh** [comment]
The black space depends on your screen resolution. Could you send me a screenshot to see whether it is “normal”? I'm not sure if “not there” is an option—white is, of course.

In your second question, I'm not fully sure what you mean. Do you expect to exit full-slide view when you switch tabs?

**Comment by Beramos** [comment]
Sorry the implementation was a bit lazy :D, it is an iframe which is a 
webpage within a webpage and the slides in presentation mode adapt to 
the width of the website and create the black spaces.

**Comment by cljansse** [comment]
I get it, so maybe making it white instead of black is the easiest solution? Here is a screenshot (I guess this is 'normal', I have the same space also under the slide).
![screenshot black space slides](https://cloud.githubusercontent.com/assets/17247269/13775095/f5ac6344-eaa2-11e5-89e1-78af5c40c6a1.png)
What I would expect is that when I change to another tab and I come back to this one, all the slides are shown again (like they are when you first visit this tab), and there is no longer just one slide open. But its certainly not a big issue. But people may not know how to get back to the overview with all the slides.

**Comment by RubenVerborgh** [comment]
I'll just set a fixed width on the element, that will fix things.

**Comment by RubenVerborgh** [comment]
@cljansse Regarding your second question, I have a thread ongoing about that with the authors of the framework: https://github.com/shower/shower/issues/228#issuecomment-164299529

**Comment by cljansse** [comment]
Great!
