### ISSUE TITLE
Open WebSlides typesetting

### ISSUE THREAD

**Issue by EstherDeLoof** [OpenWebSlides/OpenWebSlides.github.io#4]
We moeten misschien eens overleggen hoe we ons project precies willen noemen en waar we hoofdletters gebruiken.

Open Webslides
OpenWebSlides
Open WebSlides
etc.

Wat denken jullie?

**Comment by RubenVerborgh** [comment]
> We moeten misschien eens overleggen hoe we ons project precies willen noemen en waar we hoofdletters gebruiken.

My take:
"open webslides" in gewone zinnen, zoals "We stellen voor om open webslides te gebruiken."
Dubbele beginhoofdletter in titel, zoals bovenaan de pagina "Open Webslides".

Ruben

**Comment by EstherDeLoof** [comment]
Akkoord! Dan hou ik mee aan die richtlijn in mijn bijdrages.
