### ISSUE TITLE
html code bewerken van http://openwebslides.github.io/voorstel/

### ISSUE THREAD

**Issue by Beramos** [OpenWebSlides/OpenWebSlides.github.io#5]
@RubenVerborgh 
Hoe kan ik de html code aanpassen van http://openwebslides.github.io/voorstel/ ?
Ik zou een aantal javascripts willen toevoegen aan de <body> maar aangezien deze ingeladen wordt als markdown weet ik niet direct hoe ik dit moet doen.

**Comment by RubenVerborgh** [comment]
De sjablonen staan in [_layouts](https://github.com/OpenWebSlides/OpenWebSlides.github.io/tree/master/_layouts), en de markdownstukjes worden daar dan in geplaatst. Scripts toevoegen kan dus in de layout (maar wees conservatief, "een aantal" klinkt vrij zwaar :wink:)

**Comment by Beramos** [comment]
Don't worry, het was tijdelijk om annotator te testen maar ik heb het op een andere repository gedaan :stuck_out_tongue_winking_eye:
